# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2296c80b3f21d244b1c74ab79ca1399fa0414de0af373cdd729a17ff31318d0ae2931f8faa5f53d34f9e6e70a736c7692d2c939176f6ff57efcf38482d38942

test:
  secret_key_base: 1fcbb0136294da9ff8a284dfe49cbe2bebc172d4cc84531b80d29897b36ab6e1b4e434231c276aa2bf4596443007ca2e4a27638f77cd5c7a0ddcedd2c0147645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
